import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";

const oswaldSans = Oswald({
  variable: "--font-oswald-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswaldSans.variable}  antialiased`}>{children}</body>
    </html>
  );
}
